In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/churn-prediction-gym-members-dataset/gym_members_dataset.csv

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/kaggle/input/churn-prediction-gym-members-dataset/gym_members_dataset.csv")
df

,Member_ID,Name,Age,Gender,Address,Phone_Number,Membership_Type,Join_Date,Last_Visit_Date,Favorite_Exercise,Avg_Workout_Duration_Min,Avg_Calories_Burned,Total_Weight_Lifted_kg,Visits_Per_Month,Churn
0,1,NaN,19.0,Male,"Street 171, City 39",032-51510359,Quarterly,2022-07-23,2022-11-03,Pull-ups,93,214.0,13995.0,18.0,No
1,2,Shanza,19.0,Female,"Street 111, City 18",039-19243328,Monthly,2023-12-04,2024-02-14,Squats,37,436.0,4612.0,11.0,No
2,3,Ubaidullah,52.0,Male,"Street 69, City 21",033-60221501,Quarterly,2024-09-13,2024-12-07,Bench Press,98,523.0,3124.0,4.0,Yes
3,4,Mansoor Ahmed,52.0,Male,"Street 72, City 39",035-55527902,Monthly,2024-06-05,2025-02-24,Pull-ups,66,282.0,4586.0,24.0,No
4,5,Hanzala,32.0,Male,"Street 6, City 12",038-93946322,Monthly,2022-06-15,2022-12-02,Bench Press,32,522.0,16353.0,18.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,Mohammed,54.0,Male,"Street 2, City 15",036-24733357,Quarterly,2023-12-10,2024-04-27,Pull-ups,64,733.0,6082.0,14.0,No
146,147,Haseena,45.0,Female,"Street 31, City 22",038-73797777,Monthly,2023-02-10,2023-04-02,Bench Press,95,641.0,7375.0,12.0,No
147,148,Hassaan,54.0,Male,"Street 121, City 31",032-16612823,Quarterly,2023-03-27,2023-12-07,Deadlift,80,471.0,6138.0,14.0,No
148,149,Najat,26.0,Female,"Street 190, City 9",034-49625944,Monthly,2023-05-05,2024-03-26,Bench Press,50,473.0,18336.0,4.0,Yes
149,150,Nuha,43.0,Male,"Street 87, City 6",035-30033575,Yearly,2024-06-02,2025-05-22,Squats,78,608.0,12542.0,22.0,No

In [4]:
df.describe()

,Member_ID,Age,Avg_Workout_Duration_Min,Avg_Calories_Burned,Total_Weight_Lifted_kg,Visits_Per_Month
count,150.000000,137.000000,150.000000,139.000000,142.000000,138.000000
mean,75.500000,35.905109,73.326667,488.309353,9486.978873,14.224638
std,43.445368,11.654892,25.879560,168.649317,5127.955128,6.385451
min,1.000000,18.000000,30.000000,209.000000,1009.000000,4.000000
25%,38.250000,25.000000,53.000000,341.500000,5274.000000,8.000000
50%,75.500000,36.000000,74.000000,496.000000,9072.500000,14.000000
75%,112.750000,46.000000,94.500000,627.500000,13620.750000,20.000000
max,150.000000,54.000000,119.000000,788.000000,19722.000000,24.000000

In [5]:
df.describe(include="O")

,Name,Gender,Address,Phone_Number,Membership_Type,Join_Date,Last_Visit_Date,Favorite_Exercise,Churn
count,127,150,150,150,150,141,150,150,150
unique,122,2,149,150,3,131,140,6,2
top,Farah,Male,"Street 72, City 39",032-51510359,Monthly,2023-03-05,2025-03-13,Deadlift,No
freq,2,75,2,1,75,2,3,32,111

In [6]:
df.head(10)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Member_ID,Name,Age,Gender,Address,Phone_Number,Membership_Type,Join_Date,Last_Visit_Date,Favorite_Exercise,Avg_Workout_Duration_Min,Avg_Calories_Burned,Total_Weight_Lifted_kg,Visits_Per_Month,Churn
0,1,NaN,19.0,Male,"Street 171, City 39",032-51510359,Quarterly,2022-07-23,2022-11-03,Pull-ups,93,214.0,13995.0,18.0,No
1,2,Shanza,19.0,Female,"Street 111, City 18",039-19243328,Monthly,2023-12-04,2024-02-14,Squats,37,436.0,4612.0,11.0,No
2,3,Ubaidullah,52.0,Male,"Street 69, City 21",033-60221501,Quarterly,2024-09-13,2024-12-07,Bench Press,98,523.0,3124.0,4.0,Yes
3,4,Mansoor Ahmed,52.0,Male,"Street 72, City 39",035-55527902,Monthly,2024-06-05,2025-02-24,Pull-ups,66,282.0,4586.0,24.0,No
4,5,Hanzala,32.0,Male,"Street 6, City 12",038-93946322,Monthly,2022-06-15,2022-12-02,Bench Press,32,522.0,16353.0,18.0,No
5,6,Arsalan Zafar,53.0,Male,"Street 15, City 27",035-95902365,Quarterly,2022-06-07,2022-09-12,Deadlift,102,250.0,4631.0,23.0,No
6,7,Kumail,46.0,Male,"Street 35, City 1",039-95163386,Monthly,2023-05-14,2023-07-10,Squats,33,NaN,4926.0,7.0,Yes
7,8,Jahanzaib,36.0,Male,"Street 25, City 14",039-51007076,Monthly,2022-02-06,2022-05-06,Deadlift,112,722.0,18376.0,16.0,No
8,9,M. Talha,41.0,Male,"Street 170, City 15",035-81198701,Quarterly,2022-08-25,2023-08-23,Squats,42,226.0,13622.0,22.0,No
9,10,Ayesha,NaN,Female,"Street 127, City 31",034-55245029,Monthly,2022-03-24,2022-06-26,Pull-ups,74,NaN,2113.0,19.0,No

In [7]:
df.tail(10)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Member_ID,Name,Age,Gender,Address,Phone_Number,Membership_Type,Join_Date,Last_Visit_Date,Favorite_Exercise,Avg_Workout_Duration_Min,Avg_Calories_Burned,Total_Weight_Lifted_kg,Visits_Per_Month,Churn
140,141,NaN,27.0,Male,"Street 72, City 39",031-88717607,Monthly,2024-09-23,2025-04-08,Deadlift,86,274.0,2346.0,8.0,No
141,142,Tasneem,23.0,Female,"Street 61, City 38",038-39022969,Monthly,2022-11-24,2023-09-01,Bench Press,58,NaN,2224.0,21.0,No
142,143,Nawal,36.0,Female,"Street 199, City 21",037-27944764,Quarterly,2024-05-25,2025-05-15,Cycling,49,338.0,14846.0,18.0,No
143,144,NaN,18.0,Male,"Street 128, City 49",039-37003061,Yearly,2024-07-19,2024-10-06,Squats,113,538.0,10700.0,9.0,No
144,145,Sajid,22.0,Male,"Street 161, City 7",039-30173428,Yearly,2023-04-25,2023-10-27,Squats,116,441.0,7013.0,6.0,Yes
145,146,Mohammed,54.0,Male,"Street 2, City 15",036-24733357,Quarterly,2023-12-10,2024-04-27,Pull-ups,64,733.0,6082.0,14.0,No
146,147,Haseena,45.0,Female,"Street 31, City 22",038-73797777,Monthly,2023-02-10,2023-04-02,Bench Press,95,641.0,7375.0,12.0,No
147,148,Hassaan,54.0,Male,"Street 121, City 31",032-16612823,Quarterly,2023-03-27,2023-12-07,Deadlift,80,471.0,6138.0,14.0,No
148,149,Najat,26.0,Female,"Street 190, City 9",034-49625944,Monthly,2023-05-05,2024-03-26,Bench Press,50,473.0,18336.0,4.0,Yes
149,150,Nuha,43.0,Male,"Street 87, City 6",035-30033575,Yearly,2024-06-02,2025-05-22,Squats,78,608.0,12542.0,22.0,No

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Member_ID                 150 non-null    int64
 1   Name                      127 non-null    object
 2   Age                       137 non-null    float64
 3   Gender                    150 non-null    object
 4   Address                   150 non-null    object
 5   Phone_Number              150 non-null    object
 6   Membership_Type           150 non-null    object
 7   Join_Date                 141 non-null    object
 8   Last_Visit_Date           150 non-null    object
 9   Favorite_Exercise         150 non-null    object
 10  Avg_Workout_Duration_Min  150 non-null    int64
 11  Avg_Calories_Burned       139 non-null    float64
 12  Total_Weight_Lifted_kg    142 non-null    float64
 13  Visits_Per_Month          138 non-null    float64
 14  Churn                     150 non-null    object
dtypes: float64(4), int64(2), object(9)
memory usage: 17.7+ KB

In [9]:
df.isna().sum()

Member_ID                    0
Name                        23
Age                         13
Gender                       0
Address                      0
Phone_Number                 0
Membership_Type              0
Join_Date                    9
Last_Visit_Date              0
Favorite_Exercise            0
Avg_Workout_Duration_Min     0
Avg_Calories_Burned         11
Total_Weight_Lifted_kg       8
Visits_Per_Month            12
Churn                        0
dtype: int64

In [10]:
df.columns

Index(['Member_ID', 'Name', 'Age', 'Gender', 'Address', 'Phone_Number',
       'Membership_Type', 'Join_Date', 'Last_Visit_Date', 'Favorite_Exercise',
       'Avg_Workout_Duration_Min', 'Avg_Calories_Burned',
       'Total_Weight_Lifted_kg', 'Visits_Per_Month', 'Churn'],
      dtype='object')

In [11]:
 df["Phone_Number"].str.replace(r"\D", "", regex=True)
df["Phone_Number"].fillna("0")

0      032-51510359
1      039-19243328
2      033-60221501
3      035-55527902
4      038-93946322
           ...
145    036-24733357
146    038-73797777
147    032-16612823
148    034-49625944
149    035-30033575
Name: Phone_Number, Length: 150, dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Member_ID                 150 non-null    int64
 1   Name                      127 non-null    object
 2   Age                       137 non-null    float64
 3   Gender                    150 non-null    object
 4   Address                   150 non-null    object
 5   Phone_Number              150 non-null    object
 6   Membership_Type           150 non-null    object
 7   Join_Date                 141 non-null    object
 8   Last_Visit_Date           150 non-null    object
 9   Favorite_Exercise         150 non-null    object
 10  Avg_Workout_Duration_Min  150 non-null    int64
 11  Avg_Calories_Burned       139 non-null    float64
 12  Total_Weight_Lifted_kg    142 non-null    float64
 13  Visits_Per_Month          138 non-null    float64
 14  Churn                     150 non-null    object
dtypes: float64(4), int64(2), object(9)
memory usage: 17.7+ KB

In [13]:
col_f=["Age","Avg_Calories_Burned","Total_Weight_Lifted_kg","Visits_Per_Month"]
for col in col_f:
    df[col] = df[col].fillna(df[col].median())

In [14]:
df.isna().sum()

Member_ID                    0
Name                        23
Age                          0
Gender                       0
Address                      0
Phone_Number                 0
Membership_Type              0
Join_Date                    9
Last_Visit_Date              0
Favorite_Exercise            0
Avg_Workout_Duration_Min     0
Avg_Calories_Burned          0
Total_Weight_Lifted_kg       0
Visits_Per_Month             0
Churn                        0
dtype: int64

In [15]:
col_s=["Name"]
for col in col_s:
    df[col] = df[col].fillna(df[col].mode()[0])

In [16]:
df.isna().sum()

Member_ID                   0
Name                        0
Age                         0
Gender                      0
Address                     0
Phone_Number                0
Membership_Type             0
Join_Date                   9
Last_Visit_Date             0
Favorite_Exercise           0
Avg_Workout_Duration_Min    0
Avg_Calories_Burned         0
Total_Weight_Lifted_kg      0
Visits_Per_Month            0
Churn                       0
dtype: int64

In [17]:
df["Phone_Number"] = df["Phone_Number"].str.replace(r"\D", "", regex=True)
df["Phone_Number"] = df["Phone_Number"].fillna("0")
df["Phone_Number"] = df["Phone_Number"].astype("Int64")

In [18]:
df["Last_Visit_Date"]=pd.to_datetime(df["Last_Visit_Date"],dayfirst=True,errors="coerce")
df["Join_Date"]=pd.to_datetime(df["Join_Date"],dayfirst=True,errors="coerce")

/tmp/ipykernel_13/2268936663.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["Join_Date"]=pd.to_datetime(df["Join_Date"],dayfirst=True,errors="coerce")

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Member_ID                 150 non-null    int64
 1   Name                      150 non-null    object
 2   Age                       150 non-null    float64
 3   Gender                    150 non-null    object
 4   Address                   150 non-null    object
 5   Phone_Number              150 non-null    Int64
 6   Membership_Type           150 non-null    object
 7   Join_Date                 141 non-null    datetime64[ns]
 8   Last_Visit_Date           64 non-null     datetime64[ns]
 9   Favorite_Exercise         150 non-null    object
 10  Avg_Workout_Duration_Min  150 non-null    int64
 11  Avg_Calories_Burned       150 non-null    float64
 12  Total_Weight_Lifted_kg    150 non-null    float64
 13  Visits_Per_Month          150 non-null    float64
 14  Churn                     150 non-null    object
dtypes: Int64(1), datetime64[ns](2), float64(4), int64(2), object(6)
memory usage: 17.9+ KB

In [20]:
df.isnull().sum()

Member_ID                    0
Name                         0
Age                          0
Gender                       0
Address                      0
Phone_Number                 0
Membership_Type              0
Join_Date                    9
Last_Visit_Date             86
Favorite_Exercise            0
Avg_Workout_Duration_Min     0
Avg_Calories_Burned          0
Total_Weight_Lifted_kg       0
Visits_Per_Month             0
Churn                        0
dtype: int64

In [21]:
df["Last_Visit_Date"].value_counts()

Last_Visit_Date
2024-01-11    2
2024-05-08    2
2023-05-12    2
2024-08-11    2
2024-08-10    1
2024-09-02    1
2022-07-12    1
2024-03-11    1
2023-08-08    1
2022-03-11    1
2022-10-10    1
2023-07-08    1
2023-03-03    1
2024-01-05    1
2023-03-10    1
2025-05-07    1
2022-04-07    1
2022-06-10    1
2025-04-02    1
2022-12-11    1
2023-12-03    1
2024-09-10    1
2024-12-02    1
2022-04-12    1
2024-08-07    1
2024-12-01    1
2024-09-07    1
2025-08-04    1
2023-01-09    1
2024-06-10    1
2023-02-04    1
2023-09-11    1
2024-07-09    1
2025-06-02    1
2023-11-01    1
2022-02-12    1
2022-12-09    1
2023-10-07    1
2022-06-05    1
2023-05-04    1
2024-02-03    1
2024-04-04    1
2024-11-12    1
2022-08-07    1
2024-04-10    1
2024-05-01    1
2023-04-05    1
2024-07-12    1
2025-11-01    1
2024-02-01    1
2023-11-04    1
2024-04-07    1
2025-10-03    1
2023-04-09    1
2024-04-08    1
2023-11-11    1
2022-07-09    1
2022-04-10    1
2025-10-07    1
2023-07-12    1
Name: count, dtype: int64

In [22]:
df["Join_Date"].value_counts()

Join_Date
2023-03-05    2
2022-10-10    2
2024-04-13    2
2023-11-13    2
2023-02-16    2
             ..
2024-06-26    1
2023-04-09    1
2023-08-28    1
2024-06-16    1
2024-06-02    1
Name: count, Length: 131, dtype: int64

In [23]:
da_columns=["Last_Visit_Date","Join_Date"]
for col in da_columns:
    df[col].fillna(pd.Timestamp('2000-01-01'), inplace=True)

/tmp/ipykernel_13/319304139.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(pd.Timestamp('2000-01-01'), inplace=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Member_ID                 150 non-null    int64
 1   Name                      150 non-null    object
 2   Age                       150 non-null    float64
 3   Gender                    150 non-null    object
 4   Address                   150 non-null    object
 5   Phone_Number              150 non-null    Int64
 6   Membership_Type           150 non-null    object
 7   Join_Date                 150 non-null    datetime64[ns]
 8   Last_Visit_Date           150 non-null    datetime64[ns]
 9   Favorite_Exercise         150 non-null    object
 10  Avg_Workout_Duration_Min  150 non-null    int64
 11  Avg_Calories_Burned       150 non-null    float64
 12  Total_Weight_Lifted_kg    150 non-null    float64
 13  Visits_Per_Month          150 non-null    float64
 14  Churn                     150 non-null    object
dtypes: Int64(1), datetime64[ns](2), float64(4), int64(2), object(6)
memory usage: 17.9+ KB

In [25]:
df

,Member_ID,Name,Age,Gender,Address,Phone_Number,Membership_Type,Join_Date,Last_Visit_Date,Favorite_Exercise,Avg_Workout_Duration_Min,Avg_Calories_Burned,Total_Weight_Lifted_kg,Visits_Per_Month,Churn
0,1,Farah,19.0,Male,"Street 171, City 39",3251510359,Quarterly,2022-07-23,2022-03-11,Pull-ups,93,214.0,13995.0,18.0,No
1,2,Shanza,19.0,Female,"Street 111, City 18",3919243328,Monthly,2023-12-04,2000-01-01,Squats,37,436.0,4612.0,11.0,No
2,3,Ubaidullah,52.0,Male,"Street 69, City 21",3360221501,Quarterly,2024-09-13,2024-07-12,Bench Press,98,523.0,3124.0,4.0,Yes
3,4,Mansoor Ahmed,52.0,Male,"Street 72, City 39",3555527902,Monthly,2024-06-05,2000-01-01,Pull-ups,66,282.0,4586.0,24.0,No
4,5,Hanzala,32.0,Male,"Street 6, City 12",3893946322,Monthly,2022-06-15,2022-02-12,Bench Press,32,522.0,16353.0,18.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,Mohammed,54.0,Male,"Street 2, City 15",3624733357,Quarterly,2023-12-10,2000-01-01,Pull-ups,64,733.0,6082.0,14.0,No
146,147,Haseena,45.0,Female,"Street 31, City 22",3873797777,Monthly,2023-02-10,2023-02-04,Bench Press,95,641.0,7375.0,12.0,No
147,148,Hassaan,54.0,Male,"Street 121, City 31",3216612823,Quarterly,2023-03-27,2023-07-12,Deadlift,80,471.0,6138.0,14.0,No
148,149,Najat,26.0,Female,"Street 190, City 9",3449625944,Monthly,2023-05-05,2000-01-01,Bench Press,50,473.0,18336.0,4.0,Yes
149,150,Nuha,43.0,Male,"Street 87, City 6",3530033575,Yearly,2024-06-02,2000-01-01,Squats,78,608.0,12542.0,22.0,No

In [26]:
df.groupby("Gender")["Age"].mean()

Gender
Female    35.560000
Male      36.266667
Name: Age, dtype: float64

In [27]:
df.groupby("Membership_Type")["Member_ID"].count()

Membership_Type
Monthly      75
Quarterly    42
Yearly       33
Name: Member_ID, dtype: int64

In [28]:
df.groupby("Gender")["Visits_Per_Month"].sum()

Gender
Female    1071.0
Male      1060.0
Name: Visits_Per_Month, dtype: float64

In [29]:
df.groupby("Gender").agg({"Total_Weight_Lifted_kg": "mean","Visits_Per_Month": "sum"})

        Total_Weight_Lifted_kg  Visits_Per_Month
Gender
Female             9459.773333            1071.0
Male               9469.973333            1060.0

In [30]:
df.groupby("Membership_Type").agg({"Member_ID": "count","Age": "mean","Visits_Per_Month": "max","Avg_Calories_Burned": "min"})

                 Member_ID        Age  Visits_Per_Month  Avg_Calories_Burned
Membership_Type
Monthly                 75  36.920000              24.0                236.0
Quarterly               42  37.690476              24.0                209.0
Yearly                  33  31.363636              24.0                257.0

In [31]:
pd.pivot_table(df, index="Gender", columns="Membership_Type", values="Avg_Calories_Burned", aggfunc="mean")

Membership_Type     Monthly   Quarterly      Yearly
Gender
Female           510.106383  404.937500  534.083333
Male             486.142857  453.038462  527.476190

In [32]:
pd.pivot_table(df, index="Membership_Type", columns="Gender", values="Visits_Per_Month", aggfunc="sum")

Gender           Female   Male
Membership_Type
Monthly           676.0  368.0
Quarterly         212.0  393.0
Yearly            183.0  299.0

In [33]:
pd.pivot_table(df, index="Favorite_Exercise", columns="Gender", values="Avg_Workout_Duration_Min", aggfunc="mean")

Gender                Female       Male
Favorite_Exercise
Bench Press        69.142857  68.454545
Cycling            73.600000  87.250000
Deadlift           69.416667  82.600000
Pull-ups           69.076923  64.142857
Squats             74.333333  74.888889
Treadmill          82.882353  60.750000

In [34]:
pd.pivot_table(df, index="Gender",columns="Membership_Type",values=["Avg_Calories_Burned", "Visits_Per_Month"],aggfunc=["mean", "max"]
)

                               mean                                           \
                Avg_Calories_Burned                         Visits_Per_Month
Membership_Type             Monthly   Quarterly      Yearly          Monthly
Gender
Female                   510.106383  404.937500  534.083333        14.382979
Male                     486.142857  453.038462  527.476190        13.142857

                                                      max                   \
                                      Avg_Calories_Burned
Membership_Type  Quarterly     Yearly             Monthly Quarterly Yearly
Gender
Female           13.250000  15.250000               778.0     638.0  779.0
Male             15.115385  14.238095               769.0     788.0  773.0


                Visits_Per_Month
Membership_Type          Monthly Quarterly Yearly
Gender
Female                      24.0      20.0   24.0
Male                        24.0      24.0   23.0

In [35]:
pivot = pd.pivot_table(df, index="Membership_Type", values="Avg_Calories_Burned", aggfunc="mean")
pivot.sort_values(by="Avg_Calories_Burned", ascending=False)

                 Avg_Calories_Burned
Membership_Type
Yearly                    529.878788
Monthly                   501.160000
Quarterly                 434.714286